//! Workspace-level git-ops validation gate.
//!
//! Phase 3 of #454. Generates a workspace `.claude/hooks/` shell script
//! that intercepts Bash tool calls running `git commit` or `git push`
//! from within a member repo's subtree and verifies that repo has a
//! healthy mockspace bootstrap before allowing the operation through.
//!
//! The gate is workspace-authored (not aggregated): one script registered
//! against the Bash matcher, embedded with the list of member-repo
//! absolute paths at generation time. When fired, it:
//!
//! 1. Reads the Claude Code tool-input JSON from stdin.
//! 2. Checks the `tool_input.command` field; exits 0 silently if it does
//!    not look like `git commit` or `git push` (out-of-scope call).
//! 3. Resolves the active repo from `tool_input.cwd` (or `$PWD` as
//!    fallback); exits 0 silently if no member repo's tree covers it.
//! 4. Verifies the repo has `mock/`, a `cargo mock` alias in
//!    `.cargo/config.toml`, and a `core.hooksPath` set so per-repo
//!    git hooks fire.
//! 5. If healthy: silent allow. If anything is missing: structured deny
//!    with a hookSpecificOutput payload pointing at the fix.
//!
//! Defence-in-depth: per-repo git hooks (installed by mockspace
//! bootstrap) are the primary enforcement. This workspace gate covers
//! the case where the per-repo hook would not fire because the bootstrap
//! was never run or `core.hooksPath` got reset.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use crate::cmd::aggregate::HookEntry;

/// File name for the generated workspace gate script.
const GATE_SCRIPT_NAME: &str = "_workspace--mockspace-gate.sh";

/// Generate the workspace mockspace gate script and return the
/// `settings.json` entry registering it.
///
/// The script is written to `<workspace>/.claude/hooks/`. The returned
/// entry is appended to `hooks.PreToolUse[]` with matcher `Bash` so it
/// fires on every Bash tool call; the script itself decides which
/// commands warrant inspection.
///
/// `repos` is the list of `(repo_name, absolute_path)` pairs that the
/// gate should consider as "member repos" worth validating.
pub(crate) fn install_workspace_gate(
    workspace: &Path,
    repos: &[(String, String)],
) -> Result<HookEntry> {
    let hooks_dir = workspace.join(".claude/hooks");
    fs::create_dir_all(&hooks_dir).ok();
    let target = hooks_dir.join(GATE_SCRIPT_NAME);
    let body = gate_script(repos);
    fs::write(&target, body)
        .with_context(|| format!("writing {}", target.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&target)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&target, perms)?;
    }
    let abs_command = target
        .to_str()
        .ok_or_else(|| anyhow::anyhow!("non-utf8 path: {}", target.display()))?
        .to_string();
    Ok(HookEntry {
        matcher: "Bash".to_string(),
        command: abs_command,
    })
}

/// True if `entry` looks like the workspace-gate entry homma manages.
/// Identification is by command-path basename so absolute and relative
/// path forms both match cleanly across regens.
pub(crate) fn is_workspace_gate_entry(entry: &serde_json::Value) -> bool {
    let hooks = match entry.get("hooks").and_then(|h| h.as_array()) {
        Some(h) => h,
        None => return false,
    };
    hooks.iter().any(|h| {
        let cmd = h
            .get("command")
            .and_then(|c| c.as_str())
            .unwrap_or("");
        is_workspace_gate_command(cmd)
    })
}

/// True if a single hook command string points at the workspace-gate
/// script. The per-hook flavour of [`is_workspace_gate_entry`]; used
/// when filtering hooks individually within a multi-hook entry.
pub(crate) fn is_workspace_gate_command(cmd: &str) -> bool {
    cmd.rsplit('/').next().unwrap_or(cmd) == GATE_SCRIPT_NAME
}

/// Render the gate script body with the workspace's member-repo list
/// baked in. The script is portable bash (>=3.2, the macOS default).
fn gate_script(repos: &[(String, String)]) -> String {
    let mut repo_table = String::new();
    for (name, path) in repos {
        // Escape any embedded single quotes so the bash literal stays
        // well-formed for paths or names containing them.
        let entry = crate::cmd::aggregate::sh_single_quote_escape(&format!("{name}|{path}"));
        repo_table.push_str(&format!("    '{entry}'\n"));
    }

    format!(
        r##"#!/usr/bin/env bash
# Generated by `homma agent regen` (#454 phase 3).
# Workspace-level mockspace bootstrap gate.
#
# Intercepts Bash tool calls running git commit / git push from inside a
# member repo's tree and denies the call if the repo's mockspace
# bootstrap is missing or broken. Per-repo git hooks remain the primary
# enforcement; this gate covers the case where they would not fire.

set -u

INPUT=$(cat)

command_line=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)

# Out of scope: not a Bash command call.
if [ -z "$command_line" ]; then
    exit 0
fi

# Out of scope: command does not start with `git commit` or `git push`.
# Tolerate a leading subdir cd (`cd foo && git commit ...`).
case "$command_line" in
    *"git commit"*) ;;
    *"git push"*) ;;
    *) exit 0 ;;
esac

# Determine active directory: prefer tool_input.cwd, fall back to PWD.
target_dir=$(printf '%s' "$INPUT" | jq -r '.tool_input.cwd // empty' 2>/dev/null)
if [ -z "$target_dir" ]; then
    target_dir="$PWD"
fi

# Member-repo table: each entry is `<name>|<absolute_path>`.
REPOS=(
{repo_table})

# Find which repo's tree covers target_dir (longest-prefix match).
match_name=""
match_path=""
for entry in "${{REPOS[@]}}"; do
    name="${{entry%%|*}}"
    path="${{entry#*|}}"
    case "$target_dir" in
        "$path"|"$path"/*)
            # Prefer the most specific (longest) path.
            if [ "${{#path}}" -gt "${{#match_path}}" ]; then
                match_name="$name"
                match_path="$path"
            fi
            ;;
    esac
done

# Out of scope: target is not under any member repo.
if [ -z "$match_path" ]; then
    exit 0
fi

# Decide whether the repo has *partially* adopted mockspace.
# A repo with NO mockspace surface (no mock/, no alias, no
# core.hooksPath) has not adopted mockspace at all; the gate stays
# out of the way to avoid enforcing adoption on unrelated repos.
# Only flag repos where some surfaces exist but others are missing,
# i.e. actual drift.
has_mock_dir=0
has_alias=0
has_hooks_path=0

[ -d "$match_path/mock" ] && has_mock_dir=1

if [ -f "$match_path/.cargo/config.toml" ] && \
   grep -qE '^mock[[:space:]]*=' "$match_path/.cargo/config.toml"; then
    has_alias=1
fi

if [ -n "$(git -C "$match_path" config --get core.hooksPath 2>/dev/null)" ]; then
    has_hooks_path=1
fi

adoption=$((has_mock_dir + has_alias + has_hooks_path))

# Zero adoption: silent allow. The repo never opted in.
if [ "$adoption" -eq 0 ]; then
    exit 0
fi

# Full adoption: silent allow.
if [ "$adoption" -eq 3 ]; then
    exit 0
fi

# Partial adoption: drift detected; build a problems list.
problems=()
[ "$has_mock_dir" -eq 0 ] && \
    problems+=("$match_path/mock/ is missing but other mockspace surfaces are present")
[ "$has_alias" -eq 0 ] && \
    problems+=("$match_path/.cargo/config.toml: no [alias] mock entry")
[ "$has_hooks_path" -eq 0 ] && \
    problems+=("$match_path: git config core.hooksPath is not set; per-repo git hooks will not fire")

# Build a multi-line reason for the deny payload.
reason="mockspace bootstrap incomplete for repo \`$match_name\` ($match_path):"
for p in "${{problems[@]}}"; do
    reason+=$'\n  - '"$p"
done
reason+=$'\n'"Run \`homma agent regen --repo $match_name\` to fix."

# Emit a structured deny so Claude Code surfaces it cleanly.
# `jq -Rs .` JSON-encodes stdin as a quoted string; trim the outer
# quotes since our format string already supplies them.
escaped=$(printf '%s' "$reason" | jq -Rs . | sed 's/^"//;s/"$//')
printf '{{"hookSpecificOutput":{{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}}}\n' \
    "$escaped"
exit 0
"##,
        repo_table = repo_table.trim_end(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn install_writes_executable_script_and_returns_entry() {
        let dir = tempfile::tempdir().unwrap();
        let workspace = dir.path();
        let repos = vec![
            ("arvo".to_string(), "/Users/x/Dev/clause-dev/arvo".to_string()),
            ("notko".to_string(), "/Users/x/Dev/clause-dev/notko".to_string()),
        ];
        let entry = install_workspace_gate(workspace, &repos).unwrap();
        assert_eq!(entry.matcher, "Bash");
        assert!(
            entry.command.ends_with("/.claude/hooks/_workspace--mockspace-gate.sh"),
            "expected absolute path, got: {}",
            entry.command,
        );

        let script = workspace.join(".claude/hooks/_workspace--mockspace-gate.sh");
        assert!(script.exists());
        let body = fs::read_to_string(&script).unwrap();
        assert!(body.starts_with("#!/usr/bin/env bash"));
        assert!(body.contains("'arvo|/Users/x/Dev/clause-dev/arvo'"));
        assert!(body.contains("'notko|/Users/x/Dev/clause-dev/notko'"));
        assert!(body.contains("git commit"));
        assert!(body.contains("git push"));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(&script).unwrap().permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "script not executable: mode {mode:o}");
        }
    }

    #[test]
    fn is_workspace_gate_entry_matches_managed_path() {
        let e = serde_json::json!({
            "matcher": "Bash",
            "hooks": [{ "type": "command", "command": ".claude/hooks/_workspace--mockspace-gate.sh" }]
        });
        assert!(is_workspace_gate_entry(&e));
    }

    #[test]
    fn is_workspace_gate_entry_rejects_other_paths() {
        let e = serde_json::json!({
            "matcher": "Bash",
            "hooks": [{ "type": "command", "command": ".claude/hooks/arvo--no-alloc.sh" }]
        });
        assert!(!is_workspace_gate_entry(&e));
    }

    #[test]
    fn script_body_includes_workspace_repo_paths() {
        let repos = vec![
            ("arvo".to_string(), "/abs/arvo".to_string()),
            ("hilavitkutin".to_string(), "/abs/hilavitkutin".to_string()),
        ];
        let body = gate_script(&repos);
        assert!(body.contains("'arvo|/abs/arvo'"));
        assert!(body.contains("'hilavitkutin|/abs/hilavitkutin'"));
    }

    #[test]
    fn script_body_handles_empty_repo_list() {
        let body = gate_script(&[]);
        assert!(body.contains("REPOS=("));
        assert!(body.contains("git commit"));
    }
}
