//! Workspace-level git-ops validation gate.
//!
//! Phase 3 of #454. Generates a workspace `.claude/hooks/` shell script
//! that intercepts Bash tool calls running `git commit` or `git push`
//! from within a member repo's subtree and verifies that repo has a
//! healthy mockspace bootstrap before allowing the operation through.
//!
//! The gate is workspace-authored (not aggregated): one script registered
//! against the Bash matcher, embedded with the list of member-repo
//! absolute paths at generation time. When fired, it:
//!
//! 1. Reads the Claude Code tool-input JSON from stdin.
//! 2. Checks the `tool_input.command` field; exits 0 silently if it does
//!    not look like `git commit` or `git push` (out-of-scope call).
//! 3. Resolves the active repo from `tool_input.cwd` (or `$PWD` as
//!    fallback); exits 0 silently if no member repo's tree covers it.
//! 4. Verifies the repo has `mock/`, a config marker (a launcher pin in
//!    `mockspace.toml`, or the legacy `cargo mock` alias in
//!    `.cargo/config.toml`), and a `core.hooksPath` set so per-repo git
//!    hooks fire.
//! 5. If healthy: silent allow. If anything is missing: structured deny
//!    with a hookSpecificOutput payload pointing at the fix.
//!
//! Defence-in-depth: per-repo git hooks (installed by mockspace
//! bootstrap) are the primary enforcement. This workspace gate covers
//! the case where the per-repo hook would not fire because the bootstrap
//! was never run or `core.hooksPath` got reset.

use anyhow::{Context, Result};

use crate::cmd::aggregate::HookEntry;

/// File name for the generated workspace gate script.
const GATE_SCRIPT_NAME: &str = "_workspace--mockspace-gate.sh";

/// Generate the workspace mockspace gate script and return the
/// `settings.json` entry registering it.
///
/// The script is written to `<workspace>/.claude/hooks/`. The returned
/// entry is appended to `hooks.PreToolUse[]` with matcher `Bash` so it
/// fires on every Bash tool call; the script itself decides which
/// commands warrant inspection.
///
/// `repos` is the list of `(repo_name, absolute_path)` pairs that the
/// gate should consider as "member repos" worth validating.
pub(crate) fn install_workspace_gate(
    root: &homma_api::Root,
    repos: &[(String, String)],
) -> Result<HookEntry> {
    // Proven, like every other write this pass performs. This one installs an
    // executable the agent harness then runs on every tool call, which is the
    // write with the largest consequence in the program.
    let hooks_dir = root
        .contain(&root.as_abs().join(".claude/hooks"))
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    root.create_dir_all(&hooks_dir).ok();
    let target = root
        .contain_under(&hooks_dir, GATE_SCRIPT_NAME)
        .map_err(|e| anyhow::anyhow!("{e}"))?;
    let body = gate_script(repos);
    root.write(&target, body)
        .with_context(|| format!("writing {}", target.as_path().display()))?;
    #[cfg(unix)]
    root.set_executable(&target)?;
    let abs_command = target
        .as_path()
        .to_str()
        .ok_or_else(|| anyhow::anyhow!("non-utf8 path: {}", target.as_path().display()))?
        .to_string();
    Ok(HookEntry {
        matcher: "Bash".to_string(),
        command: abs_command,
    })
}

/// True if a single hook command string points at the workspace-gate
/// script. Used by `merge_settings` when filtering hooks individually
/// within a multi-hook entry. Identification is by command-path
/// basename so absolute and relative path forms both match cleanly
/// across regens.
pub(crate) fn is_workspace_gate_command(cmd: &str) -> bool {
    cmd.rsplit('/').next().unwrap_or(cmd) == GATE_SCRIPT_NAME
}

/// Render the gate script body with the workspace's member-repo list
/// baked in. The script is portable bash (>=3.2, the macOS default).
fn gate_script(repos: &[(String, String)]) -> String {
    let mut repo_table = String::new();
    for (name, path) in repos {
        // Escape any embedded single quotes so the bash literal stays
        // well-formed for paths or names containing them.
        let entry = crate::cmd::aggregate::sh_single_quote_escape(&format!("{name}|{path}"));
        repo_table.push_str(&format!("    '{entry}'\n"));
    }

    format!(
        r##"#!/usr/bin/env bash
# Generated by `homma agent regen` (#454 phase 3).
# Workspace-level mockspace bootstrap gate.
#
# Intercepts Bash tool calls running git commit / git push from inside a
# member repo's tree and denies the call if the repo's mockspace
# bootstrap is missing or broken. Per-repo git hooks remain the primary
# enforcement; this gate covers the case where they would not fire.

set -u

INPUT=$(cat)

command_line=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)

# Out of scope: not a Bash command call.
if [ -z "$command_line" ]; then
    exit 0
fi

# Out of scope: command does not start with `git commit` or `git push`.
# Tolerate a leading subdir cd (`cd foo && git commit ...`).
case "$command_line" in
    *"git commit"*) ;;
    *"git push"*) ;;
    *) exit 0 ;;
esac

# Determine active directory: prefer tool_input.cwd, fall back to PWD.
target_dir=$(printf '%s' "$INPUT" | jq -r '.tool_input.cwd // empty' 2>/dev/null)
if [ -z "$target_dir" ]; then
    target_dir="$PWD"
fi

# Member-repo table: each entry is `<name>|<absolute_path>`.
REPOS=(
{repo_table})

# Find which repo's tree covers target_dir (longest-prefix match).
match_name=""
match_path=""
for entry in "${{REPOS[@]}}"; do
    name="${{entry%%|*}}"
    path="${{entry#*|}}"
    case "$target_dir" in
        "$path"|"$path"/*)
            # Prefer the most specific (longest) path.
            if [ "${{#path}}" -gt "${{#match_path}}" ]; then
                match_name="$name"
                match_path="$path"
            fi
            ;;
    esac
done

# Out of scope: target is not under any member repo.
if [ -z "$match_path" ]; then
    exit 0
fi

# The mockspace tool repo is not a mockspace *consumer*. Its mock/ is v2
# self-hosting and its v1 src is intentionally ungated (no core.hooksPath),
# so it always scores partial adoption by design, not drift. Skip the gate
# for it, identified by its own Cargo package name.
if [ "$match_name" = "mockspace" ] \
    && grep -qE '^name[[:space:]]*=[[:space:]]*"mockspace"[[:space:]]*$' "$match_path/Cargo.toml" 2>/dev/null; then
    exit 0
fi

# Decide whether the repo has *partially* adopted mockspace.
# A repo with NO mockspace surface (no mock/, no alias, no
# core.hooksPath) has not adopted mockspace at all; the gate stays
# out of the way to avoid enforcing adoption on unrelated repos.
# Only flag repos where some surfaces exist but others are missing,
# i.e. actual drift.
has_mock_dir=0
has_alias=0
has_pin=0
has_hooks_path=0

[ -d "$match_path/mock" ] && has_mock_dir=1

if [ -f "$match_path/.cargo/config.toml" ]; then
    # Section-aware: only count `mock = ...` lines that appear under
    # the `[alias]` table header. A bare `mock = ...` under any other
    # section (e.g. `[envs]`) is not the cargo alias the bootstrap
    # writes and should not satisfy the adoption check. awk's state
    # machine handles the section tracking cleanly without pulling
    # in a TOML parser.
    alias_hit=$(awk '
        /^\[alias\][[:space:]]*$/ {{ in_alias=1; next }}
        /^\[[^]]+\][[:space:]]*$/ {{ in_alias=0; next }}
        in_alias && /^[[:space:]]*mock[[:space:]]*=/ {{ print "1"; exit }}
    ' "$match_path/.cargo/config.toml")
    [ "$alias_hit" = "1" ] && has_alias=1
fi

if [ -n "$(git -C "$match_path" config --get core.hooksPath 2>/dev/null)" ]; then
    has_hooks_path=1
fi

# The launcher+pin model has no `[alias] mock`; its config marker is a
# top-level `mockspace_*` pin in a root or mock/ mockspace.toml. Either the
# legacy alias OR a launcher pin satisfies the "config present" surface.
for cfg in "$match_path/mockspace.toml" "$match_path/mock/mockspace.toml"; do
    [ -f "$cfg" ] || continue
    pin_hit=$(awk '
        /^\[/ {{ exit }}
        /^[[:space:]]*mockspace_(version|branch|rev|tag)[[:space:]]*=/ {{ print "1"; exit }}
    ' "$cfg")
    [ "$pin_hit" = "1" ] && {{ has_pin=1; break; }}
done
if [ "$has_alias" -eq 1 ] || [ "$has_pin" -eq 1 ]; then has_config=1; else has_config=0; fi

adoption=$((has_mock_dir + has_config + has_hooks_path))

# Zero adoption: silent allow. The repo never opted in.
if [ "$adoption" -eq 0 ]; then
    exit 0
fi

# Full adoption: silent allow.
if [ "$adoption" -eq 3 ]; then
    exit 0
fi

# Partial adoption: drift detected; build a problems list.
problems=()
[ "$has_mock_dir" -eq 0 ] && \
    problems+=("$match_path/mock/ is missing but other mockspace surfaces are present")
[ "$has_config" -eq 0 ] && \
    problems+=("$match_path: no launcher pin (mockspace_* in mockspace.toml) and no legacy [alias] mock entry")
[ "$has_hooks_path" -eq 0 ] && \
    problems+=("$match_path: git config core.hooksPath is not set; per-repo git hooks will not fire")

# Build a multi-line reason for the deny payload.
reason="mockspace bootstrap incomplete for repo \`$match_name\` ($match_path):"
for p in "${{problems[@]}}"; do
    reason+=$'\n  - '"$p"
done
reason+=$'\n'"Run \`homma agent regen --repo $match_name\` to fix."

# Emit a structured deny so Claude Code surfaces it cleanly.
# `jq -Rs .` JSON-encodes stdin as a quoted string; trim the outer
# quotes since our format string already supplies them.
escaped=$(printf '%s' "$reason" | jq -Rs . | sed 's/^"//;s/"$//')
printf '{{"hookSpecificOutput":{{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}}}\n' \
    "$escaped"
exit 0
"##,
        repo_table = repo_table.trim_end(),
    )
}

#[cfg(test)]
mod tests {

    /// A `Root` over a test workspace, denying nothing that a test uses.
    ///
    /// The real code path, not a variant of it: these go through
    /// `Root::contain` exactly as production does, which is what makes the
    /// containment they assert mean anything.
    fn test_root(workspace: &Path) -> homma_api::Root {
        homma_api::Root::new(
            &homma_api::AbsPath::new(workspace).expect("a tempdir path is absolute"),
            homma_api::Denied::under_home(&homma_api::AbsPath::new("/nonexistent-home").unwrap()),
        )
        .expect("a tempdir is a legitimate root")
    }
    use super::*;

    #[test]
    fn install_writes_executable_script_and_returns_entry() {
        let dir = tempfile::tempdir().unwrap();
        let workspace = dir.path();
        let repos = vec![
            (
                "arvo".to_string(),
                "/Users/x/Dev/clause-dev/arvo".to_string(),
            ),
            (
                "notko".to_string(),
                "/Users/x/Dev/clause-dev/notko".to_string(),
            ),
        ];
        let entry = install_workspace_gate(&test_root(workspace), &repos).unwrap();
        assert_eq!(entry.matcher, "Bash");
        assert!(
            entry
                .command
                .ends_with("/.claude/hooks/_workspace--mockspace-gate.sh"),
            "expected absolute path, got: {}",
            entry.command,
        );

        let script = workspace.join(".claude/hooks/_workspace--mockspace-gate.sh");
        assert!(script.exists());
        let body = fs::read_to_string(&script).unwrap();
        assert!(body.starts_with("#!/usr/bin/env bash"));
        assert!(body.contains("'arvo|/Users/x/Dev/clause-dev/arvo'"));
        assert!(body.contains("'notko|/Users/x/Dev/clause-dev/notko'"));
        assert!(body.contains("git commit"));
        assert!(body.contains("git push"));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(&script).unwrap().permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "script not executable: mode {mode:o}");
        }
    }

    #[test]
    fn is_workspace_gate_command_matches_managed_path() {
        assert!(is_workspace_gate_command(
            ".claude/hooks/_workspace--mockspace-gate.sh"
        ));
    }

    #[test]
    fn is_workspace_gate_command_rejects_other_paths() {
        assert!(!is_workspace_gate_command(
            ".claude/hooks/arvo--no-alloc.sh"
        ));
    }

    #[test]
    fn script_body_includes_workspace_repo_paths() {
        let repos = vec![
            ("arvo".to_string(), "/abs/arvo".to_string()),
            ("hilavitkutin".to_string(), "/abs/hilavitkutin".to_string()),
        ];
        let body = gate_script(&repos);
        assert!(body.contains("'arvo|/abs/arvo'"));
        assert!(body.contains("'hilavitkutin|/abs/hilavitkutin'"));
    }

    #[test]
    fn script_body_handles_empty_repo_list() {
        let body = gate_script(&[]);
        assert!(body.contains("REPOS=("));
        assert!(body.contains("git commit"));
    }

    // -------------------------------------------------------------------
    // End-to-end bash-execution tests for the rendered gate script. The
    // script reads JSON from stdin via `jq`, walks the workspace's
    // member-repo table to find a covering repo, then probes that
    // repo's mockspace adoption surfaces (`mock/` dir, `cargo mock`
    // alias under `[alias]` in `.cargo/config.toml`, and
    // `core.hooksPath` git config). All exit codes are 0; the
    // allow/deny signal travels through stdout's JSON payload.
    //
    // Each test renders the script via gate_script(), writes it to a
    // temp file, builds a synthetic repo tree with whichever surfaces
    // the case wants present, then invokes `bash <script>` with
    // synthesised INPUT JSON. Tests skip cleanly when bash or jq are
    // not on PATH (CI machines and developer boxes that lack them).
    // -------------------------------------------------------------------

    /// Synthesise an INPUT JSON payload matching the Claude Code Bash
    /// tool-call shape the gate script parses.
    fn input_json(command: &str, cwd: &str) -> String {
        serde_json::json!({
            "tool_input": {
                "command": command,
                "cwd": cwd,
            }
        })
        .to_string()
    }

    /// Run the gate script with the given INPUT and return stdout.
    /// Returns `None` when bash or jq are not available; callers
    /// should skip the assertion in that case.
    fn run_gate(repos: &[(String, String)], input: &str) -> Option<String> {
        use std::io::Write;
        use std::process::{Command, Stdio};

        if Command::new("bash").arg("--version").output().is_err() {
            return None;
        }
        if Command::new("jq").arg("--version").output().is_err() {
            return None;
        }

        let dir = tempfile::tempdir().unwrap();
        let script_path = dir.path().join("gate.sh");
        fs::write(&script_path, gate_script(repos)).unwrap();

        let mut child = Command::new("bash")
            .arg(&script_path)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .ok()?;
        child
            .stdin
            .as_mut()
            .unwrap()
            .write_all(input.as_bytes())
            .unwrap();
        let out = child.wait_with_output().ok()?;
        Some(String::from_utf8_lossy(&out.stdout).into_owned())
    }

    /// Build a fake repo tree with a tunable set of mockspace surfaces.
    /// Returns the repo's absolute path.
    fn fake_repo(
        parent: &Path,
        name: &str,
        with_mock_dir: bool,
        alias_shape: AliasShape,
        with_hooks_path: bool,
    ) -> std::path::PathBuf {
        let repo = parent.join(name);
        fs::create_dir_all(&repo).unwrap();

        if with_mock_dir {
            fs::create_dir_all(repo.join("mock")).unwrap();
        }

        match alias_shape {
            AliasShape::None => {}
            AliasShape::UnderAlias => {
                let cfg = repo.join(".cargo/config.toml");
                fs::create_dir_all(cfg.parent().unwrap()).unwrap();
                fs::write(&cfg, "[alias]\nmock = \"run -p mock-cli --\"\n").unwrap();
            }
            AliasShape::UnderOtherSection => {
                let cfg = repo.join(".cargo/config.toml");
                fs::create_dir_all(cfg.parent().unwrap()).unwrap();
                // `mock = ...` at top-level outside any section AND
                // `mock = ...` under an unrelated section. Neither
                // satisfies the section-aware alias check.
                fs::write(&cfg, "[envs]\nmock = \"some-other-value\"\n").unwrap();
            }
        }

        if with_hooks_path {
            std::process::Command::new("git")
                .args(["init", "--quiet"])
                .current_dir(&repo)
                .output()
                .unwrap();
            std::process::Command::new("git")
                .args(["config", "core.hooksPath", "mock/target/hooks"])
                .current_dir(&repo)
                .output()
                .unwrap();
        }

        repo
    }

    enum AliasShape {
        None,
        UnderAlias,
        UnderOtherSection,
    }

    #[test]
    fn gate_e2e_full_adoption_emits_no_deny() {
        let dir = tempfile::tempdir().unwrap();
        let repo = fake_repo(dir.path(), "arvo", true, AliasShape::UnderAlias, true);
        let repos = vec![("arvo".to_string(), repo.to_string_lossy().to_string())];
        let input = input_json("git commit -m hi", &repo.to_string_lossy());
        let Some(out) = run_gate(&repos, &input) else {
            return; // bash or jq missing; skip
        };
        assert!(
            !out.contains("\"permissionDecision\":\"deny\""),
            "full adoption should not deny; got: {out}",
        );
    }

    #[test]
    fn gate_e2e_launcher_pin_counts_as_config_marker() {
        // launcher+pin model: no `[alias] mock`, but a root mockspace.toml with
        // a `mockspace_branch` pin. With mock/ + hooksPath present, that is full
        // adoption and must not deny.
        let dir = tempfile::tempdir().unwrap();
        let repo = fake_repo(dir.path(), "arvo", true, AliasShape::None, true);
        fs::write(
            repo.join("mockspace.toml"),
            "mock_dir = \"mock\"\nmockspace_branch = \"dev\"\n",
        )
        .unwrap();
        let repos = vec![("arvo".to_string(), repo.to_string_lossy().to_string())];
        let input = input_json("git commit -m hi", &repo.to_string_lossy());
        let Some(out) = run_gate(&repos, &input) else {
            return;
        };
        assert!(
            !out.contains("\"permissionDecision\":\"deny\""),
            "launcher pin + mock/ + hooks is full adoption; should not deny; got: {out}",
        );
    }

    #[test]
    fn gate_e2e_partial_adoption_emits_deny() {
        let dir = tempfile::tempdir().unwrap();
        let repo = fake_repo(dir.path(), "arvo", true, AliasShape::None, false);
        let repos = vec![("arvo".to_string(), repo.to_string_lossy().to_string())];
        let input = input_json("git commit -m hi", &repo.to_string_lossy());
        let Some(out) = run_gate(&repos, &input) else {
            return;
        };
        assert!(
            out.contains("\"permissionDecision\":\"deny\""),
            "partial adoption (mock/ only) should deny; got: {out}",
        );
        assert!(
            out.contains("[alias] mock entry"),
            "deny reason should name the missing config marker; got: {out}",
        );
    }

    #[test]
    fn gate_e2e_zero_adoption_emits_no_deny() {
        // No mock/, no alias, no hooksPath. The gate stays out of the
        // way to avoid enforcing adoption on unrelated repos.
        let dir = tempfile::tempdir().unwrap();
        let repo = fake_repo(dir.path(), "arvo", false, AliasShape::None, false);
        let repos = vec![("arvo".to_string(), repo.to_string_lossy().to_string())];
        let input = input_json("git commit -m hi", &repo.to_string_lossy());
        let Some(out) = run_gate(&repos, &input) else {
            return;
        };
        assert!(
            !out.contains("\"permissionDecision\":\"deny\""),
            "zero adoption should be a silent allow; got: {out}",
        );
    }

    #[test]
    fn gate_e2e_alias_under_other_section_does_not_satisfy_check() {
        // The `.cargo/config.toml` has a `mock = ...` line, but it
        // appears under `[envs]` rather than `[alias]`. The
        // section-aware check should NOT count this as the cargo
        // alias the bootstrap writes. With mock/ + hooksPath both
        // present, this leaves the alias slot empty (adoption=2/3,
        // partial) and the gate should deny.
        let dir = tempfile::tempdir().unwrap();
        let repo = fake_repo(
            dir.path(),
            "arvo",
            true,
            AliasShape::UnderOtherSection,
            true,
        );
        let repos = vec![("arvo".to_string(), repo.to_string_lossy().to_string())];
        let input = input_json("git commit -m hi", &repo.to_string_lossy());
        let Some(out) = run_gate(&repos, &input) else {
            return;
        };
        assert!(
            out.contains("\"permissionDecision\":\"deny\""),
            "alias under non-[alias] section should not count; got: {out}",
        );
        assert!(
            out.contains("[alias] mock entry"),
            "deny reason should name the missing config marker; got: {out}",
        );
    }

    #[test]
    fn gate_e2e_non_git_command_is_silent_allow() {
        // Out of scope: command is not git commit / git push.
        let dir = tempfile::tempdir().unwrap();
        let repo = fake_repo(dir.path(), "arvo", true, AliasShape::None, false);
        let repos = vec![("arvo".to_string(), repo.to_string_lossy().to_string())];
        let input = input_json("ls -la", &repo.to_string_lossy());
        let Some(out) = run_gate(&repos, &input) else {
            return;
        };
        assert!(
            !out.contains("\"permissionDecision\":\"deny\""),
            "non-git command should be silent allow; got: {out}",
        );
    }
}
